# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1f427baa-4f55-4096-b8fe-6b758ce58870";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1f427baa-4f55-4096-b8fe-6b758ce58870".device = "/dev/disk/by-uuid/1f427baa-4f55-4096-b8fe-6b758ce58870";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9007-CC10";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-9638fbfe-1426-4903-bf85-68eb5ffeefe6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = false;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;

    extraPackages = with pkgs; [
      mesa
      rocmPackages.clr.icd
    ];

    extraPackages32 = with pkgs.driversi686Linux; [
      mesa
    ];
  };

  boot.kernelParams = [ "amdgpu.dc=1" ];

  environment.systemPackages = with pkgs; [
    vulkan-tools
    mesa-demos
  ];
}
